packages:
  - functions
  - src/app
  - .
allowBuilds:
  '@firebase/util': false
  esbuild: false
  protobufjs: false
  re2: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - msw
  - protobufjs
  - re2
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - framer-motion@12.40.0
  - motion-dom@12.40.0
  - motion@12.40.0
  - ts-jest@29.4.11

overrides:
  '@dataconnect/admin-generated': link:src/dataconnect-admin-generated
  '@dataconnect/generated': link:src/dataconnect-generated
  qs@<6.14.1: '>=6.14.1'
  fast-xml-parser: '>=5.3.4'
  tar: '>=7.5.13'
