name = "portfolio-danilo-final"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "VALIDATE_ENV_WARN_ONLY=1 npx @opennextjs/cloudflare build"

[vars]
VALIDATE_ENV_WARN_ONLY = "1"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
