'use server';

import OpenAI from 'openai';
import { logAdminAudit } from '@/lib/admin/audit';
import { requireAdminAccess } from '@/lib/admin/server-access';
import {
  copyInputSchema,
  type CopyInput,
  validateCopyReferenceImages,
} from '@/lib/admin/schemas/copy-agent';
import { validatePayload } from '@/lib/admin/validation';
import { getOpenAIKey } from '@/lib/admin/settings';

export type CopyAgentState = {
  success: boolean;
  /** AI-generated content (only set when aiGenerated = true). */
  content?: string;
  /** Fallback template content (only set when aiGenerated = false). */
  fallbackContent?: string;
  /** True when content was generated by AI; false when using fallback template. */
  aiGenerated?: boolean;
  error?: string;
  notice?: string;
  fieldErrors?: Record<string, string | undefined>;
};

function buildFallbackCopy(context: CopyInput): string {
  return `## 1. Project Opening
${context.projectName} was created to address a specific positioning challenge for ${context.clientName}. The creative direction was structured to sustain brand presence with clarity and consistency.

## 2. Concept and Creative Direction
The central objective was ${context.objective}. The visual narrative was oriented towards ${context.targetAudience}, prioritizing strategic decision-making and immediate reading across different usage contexts.

## 3. Visual System and Design Logic
The system was built starting from ${context.visualConcept}. The choices reinforce coherence between form and message, maintaining flexibility for evolution without losing its signature.

## 4. Applications and Experience
In execution, the main challenges were ${context.keyChallenges}. The deliverables ${context.deliverables ? `(${context.deliverables})` : ''} were conceived as an integrated ecosystem, not isolated pieces.

## 5. Closing
Result driven by direction, not excess. A project designed to remain relevant with editorial consistency and clear intent.${context.toneOfVoice ? `\n\n_Applied Tone: ${context.toneOfVoice}_` : ''}`;
}

const SYSTEM_PROMPT = `You are a portfolio case copy agent specialized in Art Direction and Visual Design projects.

## Mission
Generate winning, curated portfolio texts (modal posts and full landing pages) based on:
1. the user's project info (brief + metadata),
2. the visual materials provided (images/videos/mockups),
3. the required output fields and formats.

## Non-negotiable output rule
You MUST always output exactly the fields defined by the selected template (MODAL or LANDING PAGE).
Never omit fields. Never change field names. Never add extra sections outside the template.
If information is missing, infer carefully from visuals and write responsibly without inventing fake data (dates, metrics, awards, client approvals). Use "(not informed)" when needed.

## Writing style
- Language: Portuguese (pt-BR).
- Tone: mature, strategic, authored; emotional with restraint.
- Do NOT describe visuals literally (no "na imagem vemos...").
- Focus on intent, concept, direction, decisions, system thinking, and impact.
- Avoid empty adjectives (clean/modern/innovative) unless anchored in meaning.
- Short paragraphs, scannable, confident.

## SEO & Metadata
Always generate:
- Slug (lowercase, hyphen-separated, no accents)
- Tags (8–14, mix of craft + category + industry + deliverables)
- SEO Title (max ~60 chars)
- SEO Description (max ~155 chars)
- SEO Keywords (10–16 keywords)

## Visual analysis behavior
When visuals are provided:
- Identify: category (branding/campaign/packaging/event/digital/etc.), mood, key symbolisms, dominant palette cues, narrative tone, system applications, and intended audience.
- Use these insights to support concept & direction.

You must always ask yourself internally:
- "Does this read like a senior portfolio case?"
- "Is the concept defendable and consistent with the visuals?"
- "Did I follow the exact fields and naming?"

Deliver only the final formatted output in Markdown.
`;

export async function generateProjectCopy(
  _prevState: CopyAgentState,
  formData: FormData
): Promise<CopyAgentState> {
  const access = await requireAdminAccess().catch(() => null);
  if (!access) {
    return {
      success: false,
      error: 'SYSTEM_ERR: ADMIN_SESSION_INVALID — REAUTHENTICATE',
    };
  }
  const { supabase, user } = access;

  const rawInput: CopyInput = {
    projectName: (formData.get('projectName') as string | null)?.trim() || '',
    clientName: (formData.get('clientName') as string | null)?.trim() || '',
    objective: (formData.get('objective') as string | null)?.trim() || '',
    targetAudience:
      (formData.get('targetAudience') as string | null)?.trim() || '',
    visualConcept:
      (formData.get('visualConcept') as string | null)?.trim() || '',
    keyChallenges:
      (formData.get('keyChallenges') as string | null)?.trim() || '',
    deliverables: (formData.get('deliverables') as string | null)?.trim() || '',
    toneOfVoice: (formData.get('toneOfVoice') as string | null)?.trim() || '',
    outputType: formData.get('outputType') === 'modal' ? 'modal' : 'landing',
    youtubeUrl: (formData.get('youtubeUrl') as string | null)?.trim() || '',
  };

  const validation = validatePayload(copyInputSchema, rawInput);
  if (!validation.success) {
    return {
      success: false,
      error: validation.response.error,
    };
  }

  const context = validation.data;
  const imageEntries = formData.getAll('referenceImages');
  const referenceImages = imageEntries.filter(
    (entry): entry is File => entry instanceof File && entry.size > 0
  );

  const imageValidationError = validateCopyReferenceImages(referenceImages);
  if (imageValidationError) {
    return { success: false, error: imageValidationError };
  }

  const openApiKey = await getOpenAIKey();
  if (!openApiKey) {
    const fallbackContent = buildFallbackCopy(context);
    await logAdminAudit(supabase, user, {
      action: 'copy.generate',
      resource: 'admin_copy_agent',
      status: 'error',
      errorCode: 'missing_openai_key',
      errorMessage: 'OPENAI_API_KEY missing or not configured in database',
      metadata: { fallbackApplied: true },
    });
    return {
      success: false,
      fallbackContent,
      aiGenerated: false,
      error:
        'AI_UNAVAILABLE: OPENAI_API_KEY missing. Configure in /admin/settings to enable automatic generation.',
      notice:
        'SYSTEM_FALLBACK: A base editable draft was generated locally — without AI.',
    };
  }

  const openai = new OpenAI({ apiKey: openApiKey });

  try {
    const imageParts = await Promise.all(
      referenceImages.map(async (image) => {
        const imageBuffer = Buffer.from(await image.arrayBuffer());
        const imageBase64 = imageBuffer.toString('base64');
        return {
          type: 'image_url' as const,
          image_url: {
            url: `data:${image.type};base64,${imageBase64}`,
            detail: 'high' as const,
          },
        };
      })
    );

    // YouTube URL is sent as textual context only.
    // The model cannot access URLs — it uses the URL as an identifier/reference,
    // not as an actual video transcript. For transcript support, the caller
    // should paste the transcript text in the "Challenges" or "Concept" fields.
    let youtubeContext = '';
    if (context.youtubeUrl) {
      youtubeContext = `\nREFERENCE YOUTUBE VIDEO URL (textual context only — the model does not access the URL directly, use as project reference):\n${context.youtubeUrl}\n`;
    }

    const outputFormat =
      context.outputType === 'landing'
        ? `
### MANDATORY OUTPUT (keep field names in English)
Generate the following fields:

SLUG:
TAGS:
SEO TITLE:
SEO DESCRIPTION:
SEO KEYWORDS:

PROJECT TITLE:
SUBTITLE:
SUMMARY:
INTRODUCTION HEADLINE:
INTRODUCTION PARAGRAPHS:

BLOCK 2 · PURE TEXT (Markdown):

BLOCK 4 · QUOTE BAND:
QUOTE:
SUPPORTING TEXT:

BLOCKS 6 OR 7 · TEXT + IMAGE:
TEXT:

FINAL CTA TEXT:
`
        : `
### MANDATORY OUTPUT (keep field names in English)
Generate the following fields:

SLUG:
TAGS:
SEO TITLE:
SEO DESCRIPTION:
SEO KEYWORDS:

TITLE:
SHORT LABEL:
DESCRIPTION:
CASE BODY (Markdown):
IMAGE AND VIDEO CAPTIONS:
`;

    const userContent: any[] = [
      {
        type: 'text',
        text: [
          `OUTPUT_TYPE: ${context.outputType === 'landing' ? 'LANDING_PAGE' : 'MODAL'}`,
          '',
          'BASIC_PROJECT_DATA (JSON):',
          JSON.stringify(
            {
              'Project Name': context.projectName,
              'Client / Brand': context.clientName,
              'Project Objective': context.objective,
              'Target Audience': context.targetAudience,
              'Visual Concept': context.visualConcept,
              Challenges: context.keyChallenges,
              Deliverables: context.deliverables,
              'Desired Tone': context.toneOfVoice,
            },
            null,
            2
          ),
          '',
          youtubeContext,
          '',
          outputFormat,
          '',
          `ATTACHED_IMAGES: ${referenceImages.length}.`,
          'Generate the final text in Portuguese (pt-BR).',
        ].join('\n'),
      },
      ...imageParts,
    ];

    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userContent },
      ],
      temperature: 0.7,
    });

    const content = response.choices[0]?.message?.content || '';

    await logAdminAudit(supabase, user, {
      action: 'copy.generate',
      resource: 'admin_copy_agent',
      status: 'success',
      metadata: { model: 'gpt-4o', referenceCount: referenceImages.length },
    });

    return { success: true, content, aiGenerated: true };
  } catch (error: unknown) {
    console.error('[Admin Copy Agent] OpenAI API Error', error);
    await logAdminAudit(supabase, user, {
      action: 'copy.generate',
      resource: 'admin_copy_agent',
      status: 'error',
      errorCode: 'openai_error',
      errorMessage: error instanceof Error ? error.message : 'unknown',
    });

    const fallbackContent = buildFallbackCopy(context);
    return {
      success: false,
      fallbackContent,
      aiGenerated: false,
      error: 'SYSTEM_ERR: AI_GENERATION_FAILED — TIMEOUT_OR_API_ERROR',
      notice:
        'SYSTEM_FALLBACK: A base editable draft was generated locally — review and complete before use.',
    };
  }
}
