/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/
import * as THREE from 'three';
import React, { useEffect, useMemo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';
import { MotionValue, useReducedMotion } from 'framer-motion';

type GLTFResult = GLTF & {
  nodes: {
    Body_Ghost_White_0: THREE.Mesh;
    Eyes_Eyes_0: THREE.Mesh;
    Hat_Hat_Black_0: THREE.Mesh;
    Rim_Rim_Red_0: THREE.Mesh;
  };
  materials: {
    Ghost_White: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Hat_Black: THREE.MeshStandardMaterial;
    Rim_Red: THREE.MeshStandardMaterial;
  };
};

// Definição da interface com scrollProgress
interface GhostModelProps extends React.ComponentProps<'group'> {
  scrollProgress?: MotionValue<number>;
  scale?: number | [number, number, number];
}

export function GhostModel({ scrollProgress, ...props }: GhostModelProps) {
  const prefersReducedMotion = useReducedMotion();

  const { scene } = useGLTF(
    'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
  ) as unknown as GLTFResult;

  const { gl, viewport } = useThree();
  const groupRef = useRef<THREE.Group>(null);
  const animRef = useRef<THREE.Group>(null);
  const mouseRef = useRef({ x: 0, y: 0 });
  const basePosition = useMemo(() => {
    if (Array.isArray(props.position)) {
      const [x = 0, y = 0, z = 0] = props.position;
      return new THREE.Vector3(x, y, z);
    }
    if (props.position instanceof THREE.Vector3) {
      return props.position.clone();
    }
    return new THREE.Vector3(0, 0, 0);
  }, [props.position]);

  // Clone scene to avoid mutation issues if reused
  const ghostScene = useMemo(() => {
    const clonedScene = scene.clone();
    clonedScene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;
        child.receiveShadow = true;
        if (child.material) {
          const mat = child.material as THREE.MeshStandardMaterial;
          mat.emissive = new THREE.Color('#0048ff');
          mat.emissiveIntensity = 0.35;
          mat.roughness = 0.3;
          mat.metalness = 0.05;
        }
      }
    });
    return clonedScene;
  }, [scene]);

  useEffect(() => {
    if (prefersReducedMotion) return;
    const handleMouseMove = (event: MouseEvent) => {
      if (gl.domElement) {
        const rect = gl.domElement.getBoundingClientRect();
        const x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
        const y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
        mouseRef.current = { x, y };
      }
    };
    const canvas = gl.domElement;
    canvas.addEventListener('mousemove', handleMouseMove);
    return () => canvas.removeEventListener('mousemove', handleMouseMove);
  }, [gl, prefersReducedMotion]);

  useEffect(() => {
    if (groupRef.current) {
      groupRef.current.position.copy(basePosition);
    }
  }, [basePosition]);

  // --- Responsividade (Policy 4.3) ---
  const isMobile = viewport.width < 5;
  // Prioritize prop scale, then responsive default
  const defaultScale = isMobile ? viewport.width * 0.18 : 1.3;
  const baseScale = props.scale ? (props.scale as number) : defaultScale;

  // Handle touch interactions simply by updating mouseRef
  useEffect(() => {
    if (prefersReducedMotion) return;
    const handleTouchMove = (e: TouchEvent) => {
      if (e.touches.length > 0 && gl.domElement) {
        const touch = e.touches[0];
        const rect = gl.domElement.getBoundingClientRect();
        const x = ((touch.clientX - rect.left) / rect.width) * 2 - 1;
        const y = -((touch.clientY - rect.top) / rect.height) * 2 + 1;
        mouseRef.current = { x, y };
      }
    };

    const canvas = gl.domElement;
    canvas.addEventListener('touchmove', handleTouchMove, { passive: true });
    return () => canvas.removeEventListener('touchmove', handleTouchMove);
  }, [gl, prefersReducedMotion]);

  useFrame((state) => {
    if (!animRef.current || !groupRef.current) return;

    const progress = scrollProgress?.get?.() ?? 0;
    const mouse = prefersReducedMotion ? { x: 0, y: 0 } : mouseRef.current;
    const finalOffsetX = 0;

    groupRef.current.position.x = THREE.MathUtils.lerp(
      groupRef.current.position.x,
      basePosition.x + finalOffsetX,
      0.05
    );

    // --- Animação de Flutuação Sutil (Substituindo <Float>) ---
    const elapsedTime = state.clock.getElapsedTime();
    const floatY = prefersReducedMotion ? 0 : Math.sin(elapsedTime * 1.2) * 0.06;

    // --- Resposta ao Mouse (Posição e Rotação) ---
    const mouseInfluence = prefersReducedMotion ? 0 : 0.14;

    // Movimento suave seguindo o cursor
    animRef.current.position.x = THREE.MathUtils.lerp(
      animRef.current.position.x,
      mouse.x * mouseInfluence,
      0.05
    );
    // Combina a resposta ao mouse com a animação de flutuação
    animRef.current.position.y = THREE.MathUtils.lerp(
      animRef.current.position.y,
      mouse.y * mouseInfluence + floatY,
      0.05
    );

    // Lerp rotações X e Z baseadas no mouse (Tilt suave)
    animRef.current.rotation.x = THREE.MathUtils.lerp(
      animRef.current.rotation.x,
      -mouse.y * mouseInfluence * 0.6,
      0.05
    );
    animRef.current.rotation.z = THREE.MathUtils.lerp(
      animRef.current.rotation.z,
      -mouse.x * mouseInfluence * 0.35,
      0.05
    );

    // --- Efeitos de Final de Seção ---
    let targetScale = 1;
    if (!prefersReducedMotion && progress > 0.82) {
      const intensity = Math.min(1, (progress - 0.82) * 4);
      animRef.current.position.z = THREE.MathUtils.lerp(
        animRef.current.position.z,
        0.6 * intensity,
        0.05
      );
      targetScale = 1 + 0.08 * intensity;
    } else {
      animRef.current.position.z = THREE.MathUtils.lerp(
        animRef.current.position.z,
        0,
        0.05
      );
    }

    animRef.current.scale.setScalar(targetScale);
  });

  return (
    <group ref={groupRef} {...props} scale={baseScale} dispose={null}>
      <group ref={animRef}>
        <primitive object={ghostScene} />
      </group>
    </group>
  );
}

// Preload only in the browser to avoid Node/SSG environments where
// Web Workers (used by meshopt decoding) are unavailable.
if (typeof window !== 'undefined') {
  useGLTF.preload(
    'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
  );
}
